### ISSUE TITLE
Enforcement of adherence to original typespecs on stubbed functions?

### ISSUE THREAD

**Issue by joshrieken** [wanderanimrod/elixir_mock#9]
Is this even possible?

**Comment by wanderanimrod** [comment]
Hi @facto,

I don't think we should make the library read typespecs and force mocks to adhere to them. Elixir's `Behaviours` do something very similar to what you are trying to achieve. I would prefer we go with allowing mocks to be defined based on behaviours. I think that might be a cleaner way to get you to where you want to go.

Am I understanding you right?

**Comment by joshrieken** [comment]
Thanks, @wanderanimrod.

I think that would work great when generating mocks for modules that already implement behaviours. But not all modules do, so enforcing adherence to existing typespecs, if any, would also be useful I think.

**Comment by wanderanimrod** [comment]
Looks like [examining typespecs at runtime is possible](https://hexdocs.pm/elixir/1.0.5/Kernel.Typespec.html#content). I'll look into this and see what can be done. 

If you had to chose between Behaviours and Typespecs support, which one would you do first?

**Comment by joshrieken** [comment]
@wanderanimrod Hmm... Either would be fine. Personally, I'd probably utilize the typespecs more. I'm happy to try my hand at the typespecs if you want to split the work.

**Comment by wanderanimrod** [comment]
No it's okay. I just wanted to knw what is more pressing for you so I start with that. I'll look at the Typespecs and update this issue with progress as I go.

Thanks again for your contribution.

**Comment by wanderanimrod** [comment]
@facto ,

Whereas you can inspect typespecs attached to a function using [`Kernel.Typespec.beam_specs/1`](https://hexdocs.pm/elixir/1.0.5/Kernel.Typespec.html#beam_specs/1), you cannot force functions to completely adhere to these specs. Specifically, you cannot enforce that a function's arguments or its return value are of a certain type precisely because type information is not available at compile time in elixir. Tools like Dialyzer have a lot of elaborate tricks but still cannot catch all type-related errors at compile time. That's is why they resort to ["optimisitic type checking"](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwins43A9__WAhWl5IMKHeMxCKgQtwIIKDAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJT0ECYZ9FaQ&usg=AOvVaw2U5SvH1Bm75OaxtXLlx2cw).

ElixirMock currently [does not allow functions that don't match original module functions by name and arity](https://github.com/wanderanimrod/elixir_mock/blob/master/test/elixir_mock_tests/mock_definition_test.exs#L106). That takes care of the _arity_ aspect of type specs. It deosn't take care of the _type_ aspect for reasons explained above.

I feel therefore that the safety measures already present are as far as we can go in a dynamically typed environment.

Let me know if this is clear. I'll close this issue for now.

**Comment by joshrieken** [comment]
Yep, makes sense. Thanks.
